### ISSUE TITLE
Finish radial

### ISSUE THREAD

**Issue by severo** [severo/well-formed#2]
Normal state:

- [x] create the circle arc for every journal, put it at the right place and with the right colour
- [x] create the circle arc for every category, put it at the right place, with the right colour and show its label
- [x] create the links between arcs
- [x] add tooltips
- [x] add space for the main title (but let it empty)
- [x] verify the "rotation shift"
- [x] currently there is a problem when resizing
- [x] set exact colours (for the links)
- [x] set exact radius and padding (for the arcs)
- [ ] check why the splines are slightly different from the original.

"journal selected" state:

- [x] colour of the journals: selected -> black, linked -> modulated colour, unlinked -> grey
- [x] colour of the categories -> grey
- [x] colour of the links: linked -> colour of the source, unlinked -> hidden
- [x] journal labels: selected -> black, linked -> modulated grey, others -> hidden
- [x] category labels: hidden
- [x] tooltip on journals
- [x] tooltip on categories
- [x] title: the selected journal
- [x] set the exact colours for the links, labels

"category selected" state:

- [x] colour of the journals: linked -> modulated colour, unlinked -> grey
- [x] colour of the categories: selected -> black, others: grey
- [x] colour of the links: linked -> colour of the source, unlinked -> hidden
- [x] journal labels: from the selected category -> hidden (note: it's not stable in the original Flash application), linked -> modulated grey, other -> hidden
- [x] category labels: selected -> black, other -> hidden
- [x] tooltip
- [x] title: the selected category
- [x] set the exact colours for the links, labels
- [x] uncomment selected journal if it exists

Notes:

- [x] bug in the Flash app? -> click on the "Medecine" category first selects the "Medecine" journal, and a second click selects the category

**Comment by MoritzStefaner** [comment]
Looking great already! One thing I noticed: The multiply blendMode from the original is still missing. But if I switch it on, colors become too dark and quite pale. Are the alpha and color calculations the same? Worth checking again… (or — are you maybe drawing each link twice? A→B and B→A?
<img width="2367" alt="- 2018-07-28 at 11 01 44" src="https://user-images.githubusercontent.com/216044/43355034-b9a1c10c-9255-11e8-9f61-eef84cbf987f.png">
<img width="2128" alt="- 2018-07-28 at 11 00 59" src="https://user-images.githubusercontent.com/216044/43355035-b9bc4838-9255-11e8-9184-429338bf66a3.png">

)

**Comment by MoritzStefaner** [comment]
Also, the lines look a tiny bit to thick to me right now in default view…
<img width="2161" alt="- 2018-07-28 at 11 03 46" src="https://user-images.githubusercontent.com/216044/43355045-eb7b3d70-9255-11e8-836e-a0eb9d4e726e.png">

**Comment by severo** [comment]
Clearly, there are a lot of links drawn twice, but I understand this is the data, and the Flash application draws them twice too.
I added the blend mode, and remove a "darker()" function that had nothing to do in my code, and we are getting nearer, but it's not exactly the same. I will keep on trying.

**Comment by severo** [comment]
I think your observations have been fixed. This very slightly different now, please give me your feedback @Fil @MoritzStefaner

**Comment by MoritzStefaner** [comment]
Yes, the links look excellent now! Great work!!

(One last detail - the tooltip still seems very small :)

**Comment by severo** [comment]
Fixed

A small "scale(0.8)" escaped from my tired eyes.

**Comment by severo** [comment]
I let you close the issue if it's OK.
