### ISSUE TITLE
Style finetuning

### ISSUE THREAD

**Issue by MoritzStefaner** [severo/well-formed#4]
A few minor style issues I observed.

**Comment by MoritzStefaner** [comment]
Tooltip should have more padding
<img width="193" alt="- 2018-07-26 at 09 13 55" src="https://user-images.githubusercontent.com/216044/43247603-7a82bb30-90b5-11e8-8e1f-1aed6d6af054.png">

**Comment by MoritzStefaner** [comment]
Selection text should not be bold
<img width="206" alt="- 2018-07-26 at 09 13 26" src="https://user-images.githubusercontent.com/216044/43247617-866ffbb0-90b5-11e8-8998-93414b5c9491.png">

**Comment by MoritzStefaner** [comment]
Disable user-select for text 
<img width="1088" alt="- 2018-07-26 at 09 11 09" src="https://user-images.githubusercontent.com/216044/43247628-90a9aa0e-90b5-11e8-9e04-164543b222b8.png">

**Comment by MoritzStefaner** [comment]
SVG is slightly too large? (causes scrollbars)
<img width="1180" alt="- 2018-07-26 at 09 16 25" src="https://user-images.githubusercontent.com/216044/43247682-bdca2a22-90b5-11e8-9610-b7e20ff2219b.png">

**Comment by Fil** [comment]
Only the "padding" issue is left open.

**Comment by severo** [comment]
See https://github.com/severo/well-formed/pull/14
