### ISSUE TITLE
Tooltip in radial is smaller than in other views

### ISSUE THREAD

**Issue by MoritzStefaner** [severo/well-formed#7]

**Comment by MoritzStefaner** [comment]
<img width="834" alt="- 2018-07-28 at 10 54 05" src="https://user-images.githubusercontent.com/216044/43354969-a7b5460e-9254-11e8-8fee-27ab5792f340.png">

**Comment by severo** [comment]
Fixed with https://github.com/severo/well-formed/pull/13/commits/62c02b1d7b611107e954f20540281bd8c61d2358

**Comment by MoritzStefaner** [comment]
Yep, looks good!
